-- AlterTable
ALTER TABLE "STS" ADD COLUMN     "endTime" BIGINT NOT NULL DEFAULT 1200,
ADD COLUMN     "fine" DOUBLE PRECISION NOT NULL DEFAULT 100,
ADD COLUMN     "startTime" BIGINT NOT NULL DEFAULT 480;
