-- AlterTable
ALTER TABLE "Landfill" ALTER COLUMN "capacity" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "currentWasteVolume" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Vehicle" ALTER COLUMN "capacity" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "remainingCapacity" SET DATA TYPE DOUBLE PRECISION;
